server:
  port: 8084

spring:
  application:
    name: Video_Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyansh1711/OmegleVisonConfiguration
          clone-on-start: true