server:
  port: 8083

spring:
  application:
    name: WebRTC_Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyansh1711/OmegleVisonConfiguration
          clone-on-start: true