server:
  port: 9296

spring:
  application:
    name: Configuration_Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyansh1711/OmegleVisonConfiguration.git
          clone-on-start: true