server:
  port: 8080

spring:
  application:
    name: User_Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyansh1711/OmegleVisonConfiguration
          clone-on-start: true