server:
  port: 8086

spring:
  application:
    name: Analytics_Service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Divyansh1711/OmegleVisonConfiguration
          clone-on-start: true